name: share_plus_dialog
description: A package that improves sharing on desktop and web from the share_plus plugin with a sharing dialog
version: 1.0.2
repository: https://github.com/2-5-perceivers/share_plus_dialog

environment:
  sdk: ">=2.17.0 <3.0.0"
  # TODO: bump to 3.2.0 when available
  flutter: ">=3.0.4"

platforms:
  linux:
  windows:
  macos:
  android:
  ios:

dependencies:
  dynamic_color: ^1.4.0
  flutter:
    sdk: flutter
  share_plus: ^4.0.10
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter: