name: share_plus_dialog
description: A package that improves sharing on desktop and web from the share_plus plugin with a sharing dialog
version: 2.0.1
repository: https://github.com/2-5-perceivers/share_plus_dialog
funding:
  - https://github.com/sponsors/rares45
  - https://buymeacoffee.com/raresvanca
topics: 
  - share
  - sharing
  - dialog
  - material
screenshots:
  - description: Dialog on desktop
    path: images/dialog.png


environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=3.24.0"

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dependencies:
  flutter:
    sdk: flutter
  share_plus: ^10.0.2
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  fonts:
   - family:  SocialsIcons
     fonts:
      - asset: lib/fonts/SocialsIcons.ttf
